### ISSUE TITLE
Build fails on MacOS, could not find 'diff.h'

### ISSUE THREAD

**Issue by larryhynes** [kristapsdz/lowdown#19]
Hi

After updating the master branch, I get the following:

```
[master] ~/src/lowdown $ make
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o autolink.o autolink.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o buffer.o buffer.c
cc -g -W -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter   -c -o diff.o diff.c
diff.c:33:10: fatal error: 'diff.h' file not found
#include <diff.h>
         ^~~~~~~~
1 error generated.
make: *** [diff.o] Error 1
```

`diff(1)` on MacOS appears to be gnu diff, but perhaps header files aren't installed – I'm having trouble finding them, at any rate. Or did you have something else in mind here?

**Comment by kristapsdz** [comment]
It's a new dependency, [libdiff](https://github.com/kristapsdz/libdiff).  If you have homebrew, I just updated the [BSD.lv tap](https://github.com/kristapsdz/homebrew-repo)---can you try that out?

**Comment by larryhynes** [comment]
Great, thanks.

FYI:

```
~ $ brew tap kristapsdz/repo
==> Tapping kristapsdz/repo
Cloning into '/usr/local/Homebrew/Library/Taps/kristapsdz/homebrew-repo'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kristapsdz/homebrew-repo/divecmd.rb:7:in `<class:Divecmd>'
Please report this to the kristapsdz/repo tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/kristapsdz/homebrew-repo/divecmd.rb:8:in `<class:Divecmd>'
Please report this to the kristapsdz/repo tap!

Tapped 6 formulae (40 files, 29.2KB)
```

(I'll probably do a manual install of libdiff anyway, but nice to know there's a tap.)

Thanks again.

**Comment by kristapsdz** [comment]
Just a quick note that I've fixed the "deprecated" issues.  (I think.)  Thanks again!

**Comment by larryhynes** [comment]
Looks good!

```
~ $ brew tap kristapsdz/repo
==> Tapping kristapsdz/repo
Cloning into '/usr/local/Homebrew/Library/Taps/kristapsdz/homebrew-repo'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Tapped 6 formulae (40 files, 29.2KB)
```
